@echo off
echo Import Audit Issues to GitHub...
echo Ensure you are logged in with "gh auth login"
pause
echo Creating Labels...
call gh label create "Critical" --color "B60205" --description "Critical severity" --force
call gh label create "High" --color "D93F0B" --description "High severity" --force
call gh label create "Medium" --color "FBCA04" --description "Medium severity" --force
call gh label create "Low" --color "0E8A16" --description "Low severity" --force
call gh label create "Security" --color "FBCA04" --description "Security category" --force
call gh label create "Performance" --color "C2E0C6" --description "Performance category" --force
call gh label create "UX" --color "C5DEF5" --description "UX category" --force
call gh label create "SEO" --color "F9D0C4" --description "SEO category" --force
call gh label create "Reliability" --color "E99695" --description "Reliability category" --force
call gh label create "Analytics" --color "BFDADC" --description "Analytics category" --force
call gh label create "QA" --color "1D76DB" --description "QA category" --force
call gh label create "Data" --color "006B75" --description "Data category" --force
call gh label create "Billing" --color "5319E7" --description "Billing category" --force
call gh label create "Compliance" --color "0052CC" --description "Compliance category" --force
call gh issue create --title "[AUD-SEC-001] Missing Middleware Protection" --body "## 🔎 Finding Description\n**Audit ID:** AUD-SEC-001\n**Category:** Security\n**Effort:** S\n\n## 📝 Evidence\nNo `middleware.ts`. Route protection relies on client-side or per-page logic.\n\n## ⚠️ Risk & Impact\n**Severity:** High\n\n## 🛠 Recommended Fix\nCreate `middleware.ts` to protect `/dashboard`, `/portal` routes.\n" --label "Security,High,audit"
call gh issue create --title "[AUD-SEC-002] Missing Security Headers" --body "## 🔎 Finding Description\n**Audit ID:** AUD-SEC-002\n**Category:** Security\n**Effort:** S\n\n## 📝 Evidence\n`next.config.mjs` missing `X-Content-Type-Options`, `HSTS`, etc.\n\n## ⚠️ Risk & Impact\n**Severity:** High\n\n## 🛠 Recommended Fix\nAdd `headers()` config to `next.config.mjs`.\n" --label "Security,High,audit"
call gh issue create --title "[AUD-SEC-003] Dependency Vulnerabilities" --body "## 🔎 Finding Description\n**Audit ID:** AUD-SEC-003\n**Category:** Security\n**Effort:** S\n\n## 📝 Evidence\n`npm audit` exited with code 1.\n\n## ⚠️ Risk & Impact\n**Severity:** High\n\n## 🛠 Recommended Fix\nRun `npm audit fix`.\n" --label "Security,High,audit"
call gh issue create --title "[AUD-SEC-004] PII Logging in Webhooks" --body "## 🔎 Finding Description\n**Audit ID:** AUD-SEC-004\n**Category:** Security\n**Effort:** S\n\n## 📝 Evidence\n`api/webhooks/outseta` logs payloads with PII.\n\n## ⚠️ Risk & Impact\n**Severity:** Med\n\n## 🛠 Recommended Fix\nRemove `console.log(payload)` from webhook routes.\n" --label "Security,Med,audit"
call gh issue create --title "[AUD-SEC-005] Hardcoded Plan UIDs" --body "## 🔎 Finding Description\n**Audit ID:** AUD-SEC-005\n**Category:** Security\n**Effort:** S\n\n## 📝 Evidence\n`api/ai/concierge` has hardcoded plan IDs.\n\n## ⚠️ Risk & Impact\n**Severity:** Med\n\n## 🛠 Recommended Fix\nMove IDs to `lib/plan-config.ts` or constants.\n" --label "Security,Med,audit"
call gh issue create --title "[AUD-REL-001] No Error Monitoring" --body "## 🔎 Finding Description\n**Audit ID:** AUD-REL-001\n**Category:** Reliability\n**Effort:** M\n\n## 📝 Evidence\nSentry is missing.\n\n## ⚠️ Risk & Impact\n**Severity:** Critical\n\n## 🛠 Recommended Fix\nInstall Sentry (`npx sentry-wizard`).\n" --label "Reliability,Critical,audit"
call gh issue create --title "[AUD-ANA-001] Missing Ads Pixel" --body "## 🔎 Finding Description\n**Audit ID:** AUD-ANA-001\n**Category:** Analytics\n**Effort:** S\n\n## 📝 Evidence\nNo FB/LinkedIn/Google pixels found in `layout.tsx`.\n\n## ⚠️ Risk & Impact\n**Severity:** Critical\n\n## 🛠 Recommended Fix\nAdd pixels via `next/third-parties` or `layout.tsx`.\n" --label "Analytics,Critical,audit"
call gh issue create --title "[AUD-QA-001] Missing Automated Tests" --body "## 🔎 Finding Description\n**Audit ID:** AUD-QA-001\n**Category:** QA\n**Effort:** M\n\n## 📝 Evidence\nNo E2E tests for Auth/Signup flow.\n\n## ⚠️ Risk & Impact\n**Severity:** Critical\n\n## 🛠 Recommended Fix\nCreate Playwright test for login/signup.\n" --label "QA,Critical,audit"
call gh issue create --title "[AUD-SEO-001] Missing robots.txt" --body "## 🔎 Finding Description\n**Audit ID:** AUD-SEO-001\n**Category:** SEO\n**Effort:** S\n\n## 📝 Evidence\nFile missing.\n\n## ⚠️ Risk & Impact\n**Severity:** Critical\n\n## 🛠 Recommended Fix\nCreate `public/robots.txt`.\n" --label "SEO,Critical,audit"
call gh issue create --title "[AUD-SEO-002] Unused Schema" --body "## 🔎 Finding Description\n**Audit ID:** AUD-SEO-002\n**Category:** SEO\n**Effort:** S\n\n## 📝 Evidence\n`roles/inspector` missing Schema markup.\n\n## ⚠️ Risk & Impact\n**Severity:** Critical\n\n## 🛠 Recommended Fix\nInject JSON-LD in `app/roles/[slug]/page.tsx`.\n" --label "SEO,Critical,audit"
call gh issue create --title "[AUD-SEO-003] Incomplete Sitemap" --body "## 🔎 Finding Description\n**Audit ID:** AUD-SEO-003\n**Category:** SEO\n**Effort:** S\n\n## 📝 Evidence\n`sitemap.ts` misses dynamic routes.\n\n## ⚠️ Risk & Impact\n**Severity:** High\n\n## 🛠 Recommended Fix\nUpdate `sitemap.ts` to fetch dynamic slugs.\n" --label "SEO,High,audit"
call gh issue create --title "[AUD-SEO-004] Background Keywords" --body "## 🔎 Finding Description\n**Audit ID:** AUD-SEO-004\n**Category:** SEO\n**Effort:** S\n\n## 📝 Evidence\nHomepage title lacks \"Field Inspector Directory\".\n\n## ⚠️ Risk & Impact\n**Severity:** Med\n\n## 🛠 Recommended Fix\nUpdate `metadata` in `app/page.tsx`.\n" --label "SEO,Med,audit"
call gh issue create --title "[AUD-DB-001] Profiles vs Users Ambiguity" --body "## 🔎 Finding Description\n**Audit ID:** AUD-DB-001\n**Category:** Data\n**Effort:** M\n\n## 📝 Evidence\nCode uses `profiles`, schema defines `users`.\n\n## ⚠️ Risk & Impact\n**Severity:** Critical\n\n## 🛠 Recommended Fix\nAlign SQL schema with app code (Use `profiles`).\n" --label "Data,Critical,audit"
call gh issue create --title "[AUD-DB-002] Jobs RLS Conflict" --body "## 🔎 Finding Description\n**Audit ID:** AUD-DB-002\n**Category:** Data\n**Effort:** S\n\n## 📝 Evidence\n`jobs` has conflicting policies (Own vs Read Auth).\n\n## ⚠️ Risk & Impact\n**Severity:** Critical\n\n## 🛠 Recommended Fix\nConsolidate policies to enforce correct access.\n" --label "Data,Critical,audit"
call gh issue create --title "[AUD-DB-003] Directory Access RLS" --body "## 🔎 Finding Description\n**Audit ID:** AUD-DB-003\n**Category:** Data\n**Effort:** S\n\n## 📝 Evidence\nDirectory page fetches all profiles; RLS might block.\n\n## ⚠️ Risk & Impact\n**Severity:** Critical\n\n## 🛠 Recommended Fix\nEnsure RLS allows public/auth read of directory profiles.\n" --label "Data,Critical,audit"
call gh issue create --title "[AUD-DB-004] Missing Index: Email" --body "## 🔎 Finding Description\n**Audit ID:** AUD-DB-004\n**Category:** Data\n**Effort:** S\n\n## 📝 Evidence\nNo index on `profiles.user_email`.\n\n## ⚠️ Risk & Impact\n**Severity:** Critical\n\n## 🛠 Recommended Fix\nCreate index `idx_profiles_email`.\n" --label "Data,Critical,audit"
call gh issue create --title "[AUD-DB-005] Missing Performance Indexes" --body "## 🔎 Finding Description\n**Audit ID:** AUD-DB-005\n**Category:** Data\n**Effort:** S\n\n## 📝 Evidence\nMissing indexes on `created_at`, `subscription_tier`.\n\n## ⚠️ Risk & Impact\n**Severity:** Med\n\n## 🛠 Recommended Fix\nCreate remaining indexes.\n" --label "Data,Med,audit"
call gh issue create --title "[AUD-BIL-001] Founders Plan Mapping Gap" --body "## 🔎 Finding Description\n**Audit ID:** AUD-BIL-001\n**Category:** Billing\n**Effort:** S\n\n## 📝 Evidence\nWebhook `mapPlanToTier` misses \"Founders\" plan.\n\n## ⚠️ Risk & Impact\n**Severity:** Critical\n\n## 🛠 Recommended Fix\nupdate `api/webhooks/outseta/route.ts` mapping.\n" --label "Billing,Critical,audit"
call gh issue create --title "[AUD-PER-001] Unbounded Fetch" --body "## 🔎 Finding Description\n**Audit ID:** AUD-PER-001\n**Category:** Performance\n**Effort:** M\n\n## 📝 Evidence\n`getMembers` fetches all rows without limit.\n\n## ⚠️ Risk & Impact\n**Severity:** High\n\n## 🛠 Recommended Fix\nImplement pagination/infinite scroll + limit.\n" --label "Performance,High,audit"
call gh issue create --title "[AUD-PER-002] Client-Side Filtering" --body "## 🔎 Finding Description\n**Audit ID:** AUD-PER-002\n**Category:** Performance\n**Effort:** M\n\n## 📝 Evidence\nDirectory filters happen in JS after fetching all.\n\n## ⚠️ Risk & Impact\n**Severity:** High\n\n## 🛠 Recommended Fix\nMove filtering to Supabase query.\n" --label "Performance,High,audit"
call gh issue create --title "[AUD-UX-001] Fake Ticker Trust Signal" --body "## 🔎 Finding Description\n**Audit ID:** AUD-UX-001\n**Category:** UX\n**Effort:** S\n\n## 📝 Evidence\n\"LIVE DATA FEED\" is static.\n\n## ⚠️ Risk & Impact\n**Severity:** High\n\n## 🛠 Recommended Fix\nConnect to real data or rename to \"Recent Highlights\".\n" --label "UX,High,audit"
call gh issue create --title "[AUD-UX-002] Hidden Free Plan" --body "## 🔎 Finding Description\n**Audit ID:** AUD-UX-002\n**Category:** UX\n**Effort:** S\n\n## 📝 Evidence\nFree plan buried on homepage.\n\n## ⚠️ Risk & Impact\n**Severity:** High\n\n## 🛠 Recommended Fix\nPromote \"Join for Free\" button.\n" --label "UX,High,audit"
call gh issue create --title "[AUD-UX-003] Directory Search Gate" --body "## 🔎 Finding Description\n**Audit ID:** AUD-UX-003\n**Category:** UX\n**Effort:** M\n\n## 📝 Evidence\nSearch disabled for guests.\n\n## ⚠️ Risk & Impact\n**Severity:** High\n\n## 🛠 Recommended Fix\nAllow search, gate results (show count).\n" --label "UX,High,audit"
call gh issue create --title "[AUD-UX-004] Missing Aha Moment" --body "## 🔎 Finding Description\n**Audit ID:** AUD-UX-004\n**Category:** UX\n**Effort:** L\n\n## 📝 Evidence\nNo clear first action on dashboard.\n\n## ⚠️ Risk & Impact\n**Severity:** High\n\n## 🛠 Recommended Fix\nAdd \"Profile Completion\" or \"Find First Firm\" widget.\n" --label "UX,High,audit"
call gh issue create --title "[AUD-UX-005] Income Calculator Gate" --body "## 🔎 Finding Description\n**Audit ID:** AUD-UX-005\n**Category:** UX\n**Effort:** M\n\n## 📝 Evidence\nCalculator gated behind login.\n\n## ⚠️ Risk & Impact\n**Severity:** High\n\n## 🛠 Recommended Fix\nAllow 1 use or dummy result before gate.\n" --label "UX,High,audit"
call gh issue create --title "[AUD-UX-006] Tools Blur" --body "## 🔎 Finding Description\n**Audit ID:** AUD-UX-006\n**Category:** UX\n**Effort:** S\n\n## 📝 Evidence\nTools cards fully blurred.\n\n## ⚠️ Risk & Impact\n**Severity:** Med\n\n## 🛠 Recommended Fix\nUnblur header/desc, blur only button.\n" --label "UX,Med,audit"
call gh issue create --title "[AUD-UX-007] Mobile Pricing Stacking" --body "## 🔎 Finding Description\n**Audit ID:** AUD-UX-007\n**Category:** UX\n**Effort:** M\n\n## 📝 Evidence\n5 cards stack on mobile.\n\n## ⚠️ Risk & Impact\n**Severity:** Med\n\n## 🛠 Recommended Fix\nUse tabs or scroll snap.\n" --label "UX,Med,audit"
call gh issue create --title "[AUD-CMP-001] Missing Cookie Banner" --body "## 🔎 Finding Description\n**Audit ID:** AUD-CMP-001\n**Category:** Compliance\n**Effort:** M\n\n## 📝 Evidence\nNo banner to block tracking scripts.\n\n## ⚠️ Risk & Impact\n**Severity:** High\n\n## 🛠 Recommended Fix\nImplement Cookie Banner logic.\n" --label "Compliance,High,audit"
call gh issue create --title "[AUD-CMP-002] Privacy Links Visibility" --body "## 🔎 Finding Description\n**Audit ID:** AUD-CMP-002\n**Category:** Compliance\n**Effort:** S\n\n## 📝 Evidence\nMissing in Footer.\n\n## ⚠️ Risk & Impact\n**Severity:** Med\n\n## 🛠 Recommended Fix\nAdd links to Footer.\n" --label "Compliance,Med,audit"
echo Done!